import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Course Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p>
          Get started by editing&nbsp;
          <code>pages/index.tsx</code>
        </p>
        <div>
          <Link href={'./login'}>
            <button>Login</button>
          </Link>
        </div>
      </div>
    </>
  );
}
